<?php
// Par défaut, on met "fr"

function getLanguage($db, $user_id = null)
{
    try {
        if (!$db || !$user_id) {
            return 'en'; // Langue par défaut si la connexion à la base de données ou l'utilisateur est absent
        }
        $stmt = $db->prepare("SELECT setting_value FROM User_Settings WHERE user_id = ? AND setting_key = 'language'");
        $stmt->execute([$user_id]);
        return $stmt->fetchColumn() ?? 'fr';
    } catch (PDOException $e) {
        return 'fr';
    }
}

function getTheme($db, $user_id)
{
    try {
        $stmt = $db->prepare("SELECT setting_value FROM User_Settings WHERE user_id = ? AND setting_key = 'theme'");
        $stmt->execute([$user_id]);
        return $stmt->fetchColumn() ?? 'light';
    } catch (PDOException $e) {
        return 'light';
    }
}

// Définir la langue globale
$lang = isset($db) && isset($user_id) ? getLanguage($db, $user_id) : 'en';

$translations = [

    // FRENCH TRANSLATE
    'fr' => [
        'site_title' => 'YourTicket',
        'welcome' => 'Bienvenue sur YourTicket',
        'welcome_subtext' => 'Gérez vos tickets de support facilement',
        'create_ticket' => 'Créer un ticket',
        'create_ticket_help' => 'Soumettez une nouvelle demande d\'aide',
        'my_tickets' => 'Mes tickets',
        'my_tickets_help' => 'Consultez vos conversations en cours',
        'create' => 'Créer',
        'view' => 'Voir',
        'login_success' => 'Connexion réussie! Bienvenue',
        'logout_success' => 'Vous avez été déconnecté avec succès',
        'admin_panel' => 'Panneau d\'administration',
        'access_admin' => 'Accéder au panel',
        'fill_all_fields' => 'Veuillez remplir tous les champs',
        'ticket_created' => 'Ticket créé avec succès',
        'creation_error' => 'Erreur lors de la création',
        'title' => 'Titre',
        'message' => 'Message',
        'create_ticket_button' => 'Créer le ticket',
        'no_user_specified' => 'Aucun utilisateur spécifié',
        'user_not_found' => 'Utilisateur non trouvé',
        'user_updated' => 'Utilisateur mis à jour',
        'update_error' => 'Erreur de mise à jour',
        'settings' => 'Paramètres',
        'personal_settings' => 'Paramètres personnels',
        'save' => 'Enregistrer',
        'profile' => 'Profil',
        'login_required' => 'Connexion requise',
        'profile_of' => 'Profil de',
        'ticket' => 'Ticket',
        'new_message' => 'Nouveau message',
        'send' => 'Envoyer',
        'admin_actions' => 'Actions administratives',
        'close_ticket' => 'Fermer le Ticket',
        'light_theme' => 'Thème clair',
        'dark_theme' => 'Thème sombre',
        'full_name' => 'Nom complet',
        'select_image' => 'Sélectionner une image',
        'my_conversations' => 'Mes conversations',
        'view_conversation' => 'Voir la conversation',
        'user_management' => 'Gestion des utilisateurs',
        'ticket_management' => 'Gestion des tickets',
        'created_at' => 'Créé le',
        'profile_details' => 'Détails du profil',
        'language' => 'Langue',
        'settings_updated' => 'Paramètres mis à jour avec succès',
        'theme' => 'Thème',
        'YourTicket'          => 'YourTicket',
        'Tickets'             => 'Tickets',
        'Settings'            => 'Paramètres',
        'Profile'             => 'Mon Profil',
        'Logout'              => 'Déconnexion',
        'Admin'               => 'Admin',
        'Login'               => 'Connexion',
        'Language'            => 'Langue',
        'created_on' => 'Créé le',
        'all_rights_reserved' => 'Tous droits réservés',
        'no_users_permission' => 'Aucun utilisateur trouvé avec les permissions spécifiées',
        'change_profile_picture' => 'Changer la photo de profil',
        'profile_picture_updated' => 'Photo de profil mise à jour avec succès',
        'no_tickets' => 'Aucun ticket trouvé',
        'setting_updated' => 'Paramètre mis à jour avec succès',
        'no_tickets_found' => 'Aucun ticket trouvé',
        'ticket_not_found' => 'Ticket non trouvé',
        'ticket_closed' => 'Ticket fermé avec succès',
        'ticket_already_closed' => 'Le ticket est déjà fermé',
        'message_sent' => 'Message envoyé avec succès',
        'message_error' => 'Erreur lors de l\'envoi du message',
        'no_messages_found' => 'Aucun message trouvé',
        'update' => 'Mettre à jour',
        'email' => 'email',
        'username' => 'Nom d\'utilisateur',
        'role' => 'Rôle',
        'edit' => 'Éditer',
        'delete' => 'Supprimer',
        'permissions' => 'Permission',
        'search_users' => 'Rechercher un utilisateur',
        'search' => 'Rechercher',
        'reset' => 'Réinitialiser',
        'edit_user' => 'Éditer l\'utilisateur',
        'ticket_deleted' => 'Ticket supprimé avec succès',
    ],

    // ENGLISH TRANSLATE

    'en' => [
        'site_title' => 'YourTicket',
        'welcome' => 'Welcome to YourTicket',
        'welcome_subtext' => 'Manage your support tickets easily',
        'create_ticket' => 'Create a ticket',
        'create_ticket_help' => 'Submit a new help request',
        'my_tickets' => 'My tickets',
        'my_tickets_help' => 'Check your ongoing conversations',
        'create' => 'Create',
        'view' => 'View',
        'login_success' => 'Login successful! Welcome',
        'logout_success' => 'You have been logged out successfully',
        'admin_panel' => 'Admin panel',
        'access_admin' => 'Access the panel',
        'fill_all_fields' => 'Please fill all fields',
        'ticket_created' => 'Ticket created successfully',
        'creation_error' => 'Creation error',
        'title' => 'Title',
        'message' => 'Message',
        'create_ticket_button' => 'Create Ticket',
        'no_user_specified' => 'No user specified',
        'user_not_found' => 'User not found',
        'user_updated' => 'User updated',
        'update_error' => 'Update error',
        'settings' => 'Settings',
        'personal_settings' => 'Personal Settings',
        'save' => 'Save',
        'profile' => 'Profile',
        'login_required' => 'Login required',
        'profile_of' => 'Profile of',
        'ticket' => 'Ticket',
        'new_message' => 'New message',
        'send' => 'Send',
        'admin_actions' => 'Admin actions',
        'close_ticket' => 'Close Ticket',
        'my_conversations' => 'My Conversations',
        'view_conversation' => 'View Conversation',
        'user_management' => 'User Management',
        'ticket_management' => 'Ticket Management',
        'created_at' => 'Created At',
        'profile_details' => 'Profile Details',
        'full_name' => 'Full Name',
        'select_image' => 'Select Image',
        'light_theme' => 'Light Theme',
        'dark_theme' => 'Dark Theme',
        'YourTicket'          => 'YourTicket',
        'Tickets'             => 'Tickets',
        'Settings'            => 'Settings',
        'Profile'             => 'Profile',
        'Logout'              => 'Logout',
        'Admin'               => 'Admin',
        'Login'               => 'Login',
        'Language'            => 'Language',
        'created_on' => 'Created on',
        'all_rights_reserved' => 'All rights reserved',
        'no_users_permission' => 'No users found with the specified permissions',
        'change_profile_picture' => 'Change Profile Picture',
        'profile_picture_updated' => 'Profile picture updated successfully',
        'no_tickets' => 'No tickets found',
        'setting_updated' => 'Setting updated successfully',
        'no_tickets_found' => 'No tickets found',
        'ticket_not_found' => 'Ticket not found',
        'ticket_closed' => 'Ticket closed successfully',
        'ticket_already_closed' => 'The ticket is already closed',
        'message_sent' => 'Message sent successfully',
        'message_error' => 'Error sending message',
        'no_messages_found' => 'No messages found',
        'update' => 'Update',
        'email' => 'email',
        'username' => 'Username',
        'role' => 'Role',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'permissions' => 'Permission',
        'tickets' => 'Tickets',
        'search_users' => 'Search for a user',
        'search' => 'Search',
        'reset' => 'Reset',
        'edit_user' => 'Edit User',
        'settings_updated' => 'Settings updated successfully',
        'ticket_deleted' => 'Ticket deleted successfully',
    ],

    // DUTCH TRANSLATE

    'nl' => [
        'site_title' => 'YourTicket',
        'welcome' => 'Welkom bij YourTicket',
        'welcome_subtext' => 'Beheer uw supporttickets eenvoudig',
        'create_ticket' => 'Maak een ticket',
        'create_ticket_help' => 'Dien een nieuw hulpverzoek in',
        'my_tickets' => 'Mijn tickets',
        'my_tickets_help' => 'Bekijk uw lopende gesprekken',
        'create' => 'Aanmaken',
        'view' => 'Bekijken',
        'login_success' => 'Succesvol ingelogd! Welkom',
        'logout_success' => 'U bent succesvol uitgelogd',
        'admin_panel' => 'Beheerderspaneel',
        'access_admin' => 'Toegang tot het paneel',
        'fill_all_fields' => 'Vul alle velden in',
        'ticket_created' => 'Ticket succesvol aangemaakt',
        'creation_error' => 'Fout bij aanmaken',
        'title' => 'Titel',
        'message' => 'Bericht',
        'create_ticket_button' => 'Maak ticket',
        'no_user_specified' => 'Geen gebruiker opgegeven',
        'user_not_found' => 'Gebruiker niet gevonden',
        'user_updated' => 'Gebruiker bijgewerkt',
        'update_error' => 'Fout bij bijwerken',
        'settings' => 'Instellingen',
        'personal_settings' => 'Persoonlijke instellingen',
        'save' => 'Opslaan',
        'profile' => 'Profiel',
        'login_required' => 'Inloggen vereist',
        'profile_of' => 'Profiel van',
        'ticket' => 'Ticket',
        'new_message' => 'Nieuw bericht',
        'send' => 'Verzenden',
        'admin_actions' => 'Beheerdersacties',
        'close_ticket' => 'Sluit ticket',
        'light_theme' => 'Licht thema',
        'dark_theme' => 'Donker thema',
        'full_name' => 'Volledige naam',
        'select_image' => 'Selecteer een afbeelding',
        'my_conversations' => 'Mijn gesprekken',
        'view_conversation' => 'Bekijk gesprek',
        'user_management' => 'Gebruikersbeheer',
        'ticket_management' => 'Ticketbeheer',
        'created_at' => 'Aangemaakt op',
        'profile_details' => 'Profielgegevens',
        'language' => 'Taal',
        'settings_updated' => 'Instellingen succesvol bijgewerkt',
        'theme' => 'Thema',
        'YourTicket' => 'YourTicket',
        'Tickets' => 'Tickets',
        'Settings' => 'Instellingen',
        'Profile' => 'Profiel',
        'Logout' => 'Uitloggen',
        'Admin' => 'Beheerder',
        'Login' => 'Inloggen',
        'Language' => 'Taal',
        'created_on' => 'Aangemaakt op',
        'all_rights_reserved' => 'Alle rechten voorbehouden',
        'no_users_permission' => 'Geen gebruikers gevonden met de opgegeven rechten',
        'change_profile_picture' => 'Profielfoto wijzigen',
        'profile_picture_updated' => 'Profielfoto succesvol bijgewerkt',
        'no_tickets' => 'Geen tickets gevonden',
        'setting_updated' => 'Instelling succesvol bijgewerkt',
        'no_tickets_found' => 'Geen tickets gevonden',
        'ticket_not_found' => 'Ticket niet gevonden',
        'ticket_closed' => 'Ticket succesvol gesloten',
        'ticket_already_closed' => 'Het ticket is al gesloten',
        'message_sent' => 'Bericht succesvol verzonden',
        'message_error' => 'Fout bij verzenden van bericht',
        'no_messages_found' => 'Geen berichten gevonden',
        'update' => 'Bijwerken',
        'email' => 'email',
        'username' => 'Gebruikersnaam',
        'role' => 'Rol',
        'edit' => 'Bewerken',
        'delete' => 'Verwijderen',
        'permissions' => 'Recht',
        'tickets' => 'Tickets',
        'search_users' => 'Zoek een gebruiker',
        'search' => 'Zoeken',
        'reset' => 'Resetten',
        'edit_user' => 'Bewerk gebruiker',
        'ticket_deleted' => 'Ticket succesvol verwijderd',
    ],

    // MANDARIN TRANSLATE

    'zh' => [
        'site_title' => 'YourTicket',
        'welcome' => '欢迎来到 YourTicket',
        'welcome_subtext' => '轻松管理您的支持票',
        'create_ticket' => '创建工单',
        'create_ticket_help' => '提交新的帮助请求',
        'my_tickets' => '我的工单',
        'my_tickets_help' => '查看您正在进行的对话',
        'create' => '创建',
        'view' => '查看',
        'login_success' => '登录成功！欢迎',
        'logout_success' => '您已成功登出',
        'admin_panel' => '管理面板',
        'access_admin' => '访问面板',
        'fill_all_fields' => '请填写所有字段',
        'ticket_created' => '工单创建成功',
        'creation_error' => '创建错误',
        'title' => '标题',
        'message' => '消息',
        'create_ticket_button' => '创建工单',
        'no_user_specified' => '未指定用户',
        'user_not_found' => '未找到用户',
        'user_updated' => '用户已更新',
        'update_error' => '更新错误',
        'settings' => '设置',
        'personal_settings' => '个人设置',
        'save' => '保存',
        'profile' => '个人资料',
        'login_required' => '需要登录',
        'profile_of' => '的个人资料',
        'ticket' => '工单',
        'new_message' => '新消息',
        'send' => '发送',
        'admin_actions' => '管理操作',
        'close_ticket' => '关闭工单',
        'light_theme' => '浅色主题',
        'dark_theme' => '深色主题',
        'full_name' => '全名',
        'select_image' => '选择图片',
        'my_conversations' => '我的对话',
        'view_conversation' => '查看对话',
        'user_management' => '用户管理',
        'ticket_management' => '工单管理',
        'created_at' => '创建于',
        'profile_details' => '个人资料详情',
        'language' => '语言',
        'settings_updated' => '设置已成功更新',
        'theme' => '主题',
        'YourTicket' => 'YourTicket',
        'Tickets' => '工单',
        'Settings' => '设置',
        'Profile' => '个人资料',
        'Logout' => '登出',
        'Admin' => '管理员',
        'Login' => '登录',
        'Language' => '语言',
        'created_on' => '创建于',
        'all_rights_reserved' => '版权所有',
        'no_users_permission' => '未找到具有指定权限的用户',
        'change_profile_picture' => '更改个人资料图片',
        'profile_picture_updated' => '个人资料图片已成功更新',
        'no_tickets' => '未找到工单',
        'setting_updated' => '设置已成功更新',
        'no_tickets_found' => '未找到工单',
        'ticket_not_found' => '未找到工单',
        'ticket_closed' => '工单已成功关闭',
        'ticket_already_closed' => '工单已关闭',
        'message_sent' => '消息已成功发送',
        'message_error' => '发送消息时出错',
        'no_messages_found' => '未找到消息',
        'update' => '更新',
        'email' => '电子邮件',
        'username' => '用户名',
        'role' => '角色',
        'edit' => '编辑',
        'delete' => '删除',
        'permissions' => '权限',
        'tickets' => '工单',
        'search_users' => '搜索用户',
        'search' => '搜索',
        'reset' => '重置',
        'edit_user' => '编辑用户',
        'ticket_deleted' => '工单已成功删除',
    ],
    // PUNJABI TRANSLATE
    'pa' => [
        'site_title' => 'YourTicket',
        'welcome' => 'YourTicket ਤੇ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
        'welcome_subtext' => 'ਆਸਾਨੀ ਨਾਲ ਆਪਣੇ ਸਹਾਇਤਾ ਟਿਕਟਾਂ ਦਾ ਪ੍ਰਬੰਧ ਕਰੋ',
        'create_ticket' => 'ਟਿਕਟ ਬਣਾਓ',
        'create_ticket_help' => 'ਨਵਾਂ ਸਹਾਇਤਾ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਕਰੋ',
        'my_tickets' => 'ਮੇਰੇ ਟਿਕਟ',
        'my_tickets_help' => 'ਆਪਣੇ ਚੱਲ ਰਹੇ ਗੱਲਬਾਤਾਂ ਦੀ ਜਾਂਚ ਕਰੋ',
        'create' => 'ਬਣਾਉਣਾ',
        'view' => 'ਵੇਖੋ',
        'login_success' => 'ਲੌਗਿਨ ਸਫਲ! ਸੁਆਗਤ ਹੈ',
        'logout_success' => 'ਤੁਸੀਂ ਸਫਲਤਾਪੂਰਕ ਲੌਗਆਉਟ ਹੋ ਗਏ ਹੋ',
        'admin_panel' => 'ਐਡਮਿਨ ਪੈਨਲ',
        'access_admin' => 'ਪੈਨਲ ਤੱਕ ਪਹੁੰਚੋ',
        'fill_all_fields' => 'ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਖੇਤਰ ਭਰੋ',
        'ticket_created' => 'ਟਿਕਟ ਸਫਲਤਾਪੂਰਕ ਬਣਾਇਆ ਗਿਆ',
        'creation_error' => 'ਬਣਾਉਣ ਵਿੱਚ ਗਲਤੀ',
        'title' => 'ਸਿਰਲੇਖ',
        'message' => 'ਸੁਨੇਹਾ',
        'create_ticket_button' => 'ਟਿਕਟ ਬਣਾਓ',
        'no_user_specified' => 'ਕੋਈ ਉਪਭੋਗਤਾ ਨਿਰਧਾਰਤ ਨਹੀਂ',
        'user_not_found' => 'ਉਪਭੋਗਤਾ ਨਹੀਂ ਮਿਲਿਆ',
        'user_updated' => 'ਉਪਭੋਗਤਾ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ',
        'update_error' => 'ਅੱਪਡੇਟ ਵਿੱਚ ਗਲਤੀ',
        'settings' => 'ਸੈਟਿੰਗਾਂ',
        'personal_settings' => 'ਨਿੱਜੀ ਸੈਟਿੰਗਾਂ',
        'save' => 'ਸੁਰੱਖਿਅਤ ਕਰੋ',
        'profile' => 'ਪ੍ਰੋਫਾਈਲ',
        'login_required' => 'ਲੌਗਿਨ ਦੀ ਲੋੜ ਹੈ',
        'profile_of' => 'ਦਾ ਪ੍ਰੋਫਾਈਲ',
        'ticket' => 'ਟਿਕਟ',
        'new_message' => 'ਨਵਾਂ ਸੁਨੇਹਾ',
        'send' => 'ਭੇਜੋ',
        'admin_actions' => 'ਐਡਮਿਨ ਕਾਰਵਾਈਆਂ',
        'close_ticket' => 'ਟਿਕਟ ਬੰਦ ਕਰੋ',
        'light_theme' => 'ਹਲਕਾ ਥੀਮ',
        'dark_theme' => 'ਗੂੜ੍ਹਾ ਥੀਮ',
        'full_name' => 'ਪੂਰਾ ਨਾਮ',
        'select_image' => 'ਤਸਵੀਰ ਚੁਣੋ',
        'my_conversations' => 'ਮੇਰੀ ਗੱਲਬਾਤਾਂ',
        'view_conversation' => 'ਗੱਲਬਾਤ ਵੇਖੋ',
        'user_management' => 'ਉਪਭੋਗਤਾ ਪ੍ਰਬੰਧਨ',
        'ticket_management' => 'ਟਿਕਟ ਪ੍ਰਬੰਧਨ',
        'created_at' => 'ਤੇ ਬਣਾਇਆ ਗਿਆ',
        'profile_details' => 'ਪ੍ਰੋਫਾਈਲ ਵੇਰਵੇ',
        'language' => 'ਭਾਸ਼ਾ',
        'settings_updated' => 'ਸੈਟਿੰਗਾਂ ਸਫਲਤਾਪੂਰਕ ਅੱਪਡੇਟ ਕੀਤੀਆਂ ਗਈਆਂ',
        'theme' => 'ਥੀਮ',
        'YourTicket' => 'YourTicket',
        'Tickets' => 'ਟਿਕਟ',
        'Settings' => 'ਸੈਟਿੰਗਾਂ',
        'Profile' => 'ਪ੍ਰੋਫਾਈਲ',
        'Logout' => 'ਲੌਗਆਉਟ',
        'Admin' => 'ਐਡਮਿਨ',
        'Login' => 'ਲੌਗਿਨ',
        'Language' => 'ਭਾਸ਼ਾ',
        'created_on' => 'ਤੇ ਬਣਾਇਆ ਗਿਆ',
        'all_rights_reserved' => 'ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ',
        'no_users_permission' => 'ਨਿਰਧਾਰਤ ਅਧਿਕਾਰਾਂ ਨਾਲ ਕੋਈ ਉਪਭੋਗਤਾ ਨਹੀਂ ਮਿਲਿਆ',
        'change_profile_picture' => 'ਪ੍ਰੋਫਾਈਲ ਤਸਵੀਰ ਬਦਲੋ',
        'profile_picture_updated' => 'ਪ੍ਰੋਫਾਈਲ ਤਸਵੀਰ ਸਫਲਤਾਪੂਰਕ ਅੱਪਡੇਟ ਕੀਤੀ ਗਈ',
        'no_tickets' => 'ਕੋਈ ਟਿਕਟ ਨਹੀਂ ਮਿਲਿਆ',
        'setting_updated' => 'ਸੈਟਿੰਗ ਸਫਲਤਾਪੂਰਕ ਅੱਪਡੇਟ ਕੀਤੀ ਗਈ',
        'no_tickets_found' => 'ਕੋਈ ਟਿਕਟ ਨਹੀਂ ਮਿਲਿਆ',
        'ticket_not_found' => 'ਟਿਕਟ ਨਹੀਂ ਮਿਲਿਆ',
        'ticket_closed' => 'ਟਿਕਟ ਸਫਲਤਾਪੂਰਕ ਬੰਦ ਕੀਤਾ ਗਿਆ',
        'ticket_already_closed' => 'ਟਿਕਟ ਪਹਿਲਾਂ ਹੀ ਬੰਦ ਕੀਤਾ ਗਿਆ ਹੈ',
        'message_sent' => 'ਸੁਨੇਹਾ ਸਫਲਤਾਪੂਰਕ ਭੇਜਿਆ ਗਿਆ',
        'message_error' => 'ਸੁਨੇਹਾ ਭੇਜਣ ਵਿੱਚ ਗਲਤੀ',
        'no_messages_found' => 'ਕੋਈ ਸੁਨੇਹਾ ਨਹੀਂ ਮਿਲਿਆ',
        'update' => 'ਅੱਪਡੇਟ ਕਰੋ',
        'email' => 'ਈਮੇਲ',
        'username' => 'ਉਪਭੋਗਤਾ ਨਾਮ',
        'role' => 'ਭੂਮਿਕਾ',
        'edit' => 'ਸੋਧੋ',
        'delete' => 'ਹਟਾਓ',
        'permissions' => 'ਅਧਿਕਾਰ',
        'tickets' => 'ਟਿਕਟ',
        'search_users' => 'ਉਪਭੋਗਤਾ ਖੋਜੋ',
        'search' => 'ਖੋਜੋ',
        'reset' => 'ਰੀਸੈਟ ਕਰੋ',
        'edit_user' => 'ਉਪਭੋਗਤਾ ਸੋਧੋ',
        'ticket_deleted' => 'ਟਿਕਟ ਸਫਲਤਾਪੂਰਕ ਹਟਾਇਆ ਗਿਆ',
    ],

    // SPANISH TRANSLATE

    'es' => [
        'site_title' => 'YourTicket',
        'welcome' => 'Bienvenido a YourTicket',
        'welcome_subtext' => 'Administra tus tickets de soporte fácilmente',
        'create_ticket' => 'Crear un ticket',
        'create_ticket_help' => 'Enviar una nueva solicitud de ayuda',
        'my_tickets' => 'Mis tickets',
        'my_tickets_help' => 'Ver tus conversaciones en curso',
        'create' => 'Crear',
        'view' => 'Ver',
        'login_success' => '¡Inicio de sesión exitoso! Bienvenido',
        'logout_success' => 'Has cerrado sesión con éxito',
        'admin_panel' => 'Panel de administración',
        'access_admin' => 'Acceder al panel',
        'fill_all_fields' => 'Por favor completa todos los campos',
        'ticket_created' => 'Ticket creado con éxito',
        'creation_error' => 'Error de creación',
        'title' => 'Título',
        'message' => 'Mensaje',
        'create_ticket_button' => 'Crear ticket',
        'no_user_specified' => 'No se especificó ningún usuario',
        'user_not_found' => 'Usuario no encontrado',
        'user_updated' => 'Usuario actualizado',
        'update_error' => 'Error de actualización',
        'settings' => 'Configuraciones',
        'personal_settings' => 'Configuraciones personales',
        'save' => 'Guardar',
        'profile' => 'Perfil',
        'login_required' => 'Inicio de sesión requerido',
        'profile_of' => 'Perfil de',
        'ticket' => 'Ticket',
        'new_message' => 'Nuevo mensaje',
        'send' => 'Enviar',
        'admin_actions' => 'Acciones de administrador',
        'close_ticket' => 'Cerrar ticket',
        'light_theme' => 'Tema claro',
        'dark_theme' => 'Tema oscuro',
        'full_name' => 'Nombre completo',
        'select_image' => 'Seleccionar imagen',
        'my_conversations' => 'Mis conversaciones',
        'view_conversation' => 'Ver conversación',
        'user_management' => 'Gestión de usuarios',
        'ticket_management' => 'Gestión de tickets',
        'created_at' => 'Creado en',
        'profile_details' => 'Detalles del perfil',
        'language' => 'Idioma',
        'settings_updated' => 'Configuración actualizada con éxito',
        'theme' => 'Tema',
        'YourTicket' => 'YourTicket',
        'Tickets' => 'Tickets',
        'Settings' => 'Configuraciones',
        'Profile' => 'Perfil',
        'Logout' => 'Cerrar sesión',
        'Admin' => 'Administrador',
        'Login' => 'Iniciar sesión',
        'Language' => 'Idioma',
        'created_on' => 'Creado en',
        'all_rights_reserved' => 'Todos los derechos reservados',
        'no_users_permission' => 'No se encontraron usuarios con los permisos especificados',
        'change_profile_picture' => 'Cambiar foto de perfil',
        'profile_picture_updated' => 'Foto de perfil actualizada con éxito',
        'no_tickets' => 'No se encontraron tickets',
        'setting_updated' => 'Configuración actualizada con éxito',
        'no_tickets_found' => 'No se encontraron tickets',
        'ticket_not_found' => 'Ticket no encontrado',
        'ticket_closed' => 'Ticket cerrado con éxito',
        'ticket_already_closed' => 'El ticket ya está cerrado',
        'message_sent' => 'Mensaje enviado con éxito',
        'message_error' => 'Error al enviar el mensaje',
        'no_messages_found' => 'No se encontraron mensajes',
        'update' => 'Actualizar',
        'email' => 'correo electrónico',
        'username' => 'Nombre de usuario',
        'role' => 'Rol',
        'edit' => 'Editar',
        'delete' => 'Eliminar',
        'permissions' => 'Permisos',
        'tickets' => 'Tickets',
        'search_users' => 'Buscar un usuario',
        'search' => 'Buscar',
        'reset' => 'Restablecer',
        'edit_user' => 'Editar usuario',
        'ticket_deleted' => 'Ticket eliminado con éxito',
    ],
];

// Fonction de traduction mise à jour pour utiliser la langue globale par défaut
function t($key, $translations, $lang = 'en')
{
    global $lang; // Utiliser la langue globale
    if (!isset($translations[$lang])) {
        $lang = 'en'; // Langue par défaut si la langue globale n'est pas définie
    }
    return $translations[$lang][$key] ?? $key;
}
